version : "3.4"

services:
  database:
    image:
      postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@domen.ru"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - database
  bot:
    command: sh -c "./scripts/run.sh"
    build:
      context: bot/
    volumes:
      - ./bot/:/code/
    depends_on:
      - database
    env_file:
      - envs/bot.env
      - envs/database.env
    restart: always
  testing:
    build:
      context: .
      dockerfile: testing/Dockerfile
    volumes:
      - .:/code/
    depends_on:
      - database
    env_file:
      - envs/bot.env
      - envs/database.env

