from qa_recognition.answer_recognizers.answer_recognizer import AnswerRecognizer
from qa_recognition.answer_recognizers.a_algorithm_answer_recognizer import AAlgorithmAnswerRecognizer
from qa_recognition.answer_recognizers.b_algorithm_answer_recognizer import BAlgorithmAnswerRecognizer
from qa_recognition.answer_recognizers.c_algorithm_answer_recognizer import CAlgorithmAnswerRecognizer
from qa_recognition.answer_recognizers.d_algorithm_answer_recognizer import DAlgorithmAnswerRecognizer
from qa_recognition.answer_recognizers.network_answer_recognizer import NetworkAnswerRecognizer
