"""Initialize relations.

Revision ID: b5a3c2e4a65b
Revises: 
Create Date: 2022-04-12 14:02:55.773612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a3c2e4a65b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('QuestionAnswer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default='NOW()', nullable=True),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default='NOW()', nullable=True),
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('QuestionAnswerFlag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default='NOW()', nullable=True),
    sa.Column('qa_id', sa.Integer(), nullable=False),
    sa.Column('flag', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['qa_id'], ['QuestionAnswer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SessionLog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default='NOW()', nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('algorithm', sa.String(), nullable=False),
    sa.Column('successful', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UserRole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default='NOW()', nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_title', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserRole')
    op.drop_table('SessionLog')
    op.drop_table('QuestionAnswerFlag')
    op.drop_table('User')
    op.drop_table('QuestionAnswer')
    # ### end Alembic commands ###
